server:
  port: 20010
spring:
  datasource:
      url: jdbc:mysql://localhost:33060/query_dsl?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
      username: danmuji
      password: danmuji
      driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true

search:
  elastic:
    url: http://localhost:9200
    indexName: index04